[options]
addons_path = /mnt/extra-addons, /usr/lib/python3/dist-packages/odoo/addons
db_host = odoo-postgres
db_user = odoo
db_password = odoo
db_port = 5432
admin_passwd = $pbkdf2-sha512$600000$iTEmxFgLYeyds1bKudfaGw$/r31j2PEyk/lLWBQu2afO4CCu08IBrY1Bvght6emCnYQtxU4fdRGshOTCTg8hKJJh95VWkUVGgqE6GnJG0or3g

